#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-0 --mode 1920x1080 --rate 143.85
feh --bg-fill ~/dotfiles/wallpaper/video-games-retro-games-anime-cartoon-wallpaper-b826dc4aef3c17699e1079b222394b80.jpg
default_font="Hack Nerd Font Mono"
redshift &
udiskie &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 []=

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a firefox desktop='^2'
bspc config normal_border_color "#A6A69C"
bspc config active_border_color "#8A9A7B"
bspc config focused_border_color "#C4746E"
bspc config presel_feedback_color "#A292A3"

bspc config focus_follows_pointer true
bspc config pointer_modifier    super
