#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-0 --mode 1920x1080 --rate 143.85
feh --bg-fill --randomize ~/dotfiles/wallpaper/*
redshift &
udiskie &

$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a firefox desktop='^2'
bspc config normal_border_color "#414868"
bspc config active_border_color "#bb9af7"
bspc config focused_border_color "#e0af68"
bspc config presel_feedback_color "#7aa2f7"

bspc config focus_follows_pointer true
bspc config pointer_modifier    super

bspc config pointer_cursor Simp1e-Tokyo-Night
